version: 2.1

commands:
  restore_cypress:
    steps:
      - restore_cache:
          key: v1-cypress-binary-{{ checksum "yarn.lock" }}

  restore_functions:
    steps:
      - restore_cache:
          key: v4-functions-dependencies-{{ checksum "functions/yarn.lock" }}

  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v3-dependencies-{{ checksum "yarn.lock" }}

executors:
  node:
    docker:
      - image: cypress/base:12.14.0
    working_directory: ~/app

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - restore_functions
      - restore_cypress
      - run: yarn install
      - run: yarn cypress install
      - run: cd ~/app/functions && yarn install
      - save_cache:
          key: v3-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: v4-functions-dependencies-{{ checksum "functions/yarn.lock" }}
          paths:
            - ~/app/functions/node_modules
      - save_cache:
          key: v1-cypress-binary-{{ checksum "yarn.lock" }}
          paths:
            - /root/.cache/Cypress

  build:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn build
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist

  lint:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn lint

  test_unit:
    executor: node
    steps:
      - checkout_and_restore_cache
      - restore_functions
      - run: yarn test:unit --coverage
      - run: yarn codecov

  test_e2e:
    executor: node
    steps:
      - checkout_and_restore_cache
      - restore_cypress
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn firebase serve --only hosting -p 8080
          background: true
      - run: echo $SERVICE_ACCOUNT > ./serviceAccount.json
      - run: yarn test:e2e:ci

  deploy:
    executor: node
    steps:
      - checkout_and_restore_cache
      - attach_workspace:
          at: ~/app
      - run: yarn firebase deploy --token "${FIREBASE_TOKEN}" --only hosting

  check_pr:
    executor: node
    steps:
      - checkout
      - run: cd tools/assistant && yarn install
      - run: PR_NUMBER=${CIRCLE_PR_NUMBER} node ./tools/assistant/scripts/callChecker.js

workflows:
  version: 2
  integration:
    jobs:
      - check_pr:
          filters:
            branches:
              only: /^(pull\/).*$/
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test_unit
            # - test_e2e
          filters:
            branches:
              only: master
